---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

```{r setup, include=FALSE, error=TRUE, message=FALSE}
# Set knitr options for knitting code into the report:
# - Don't print out code (echo)
# - Save results so that code blocks aren't re-run unless code changes (cache),
# _or_ a relevant earlier code block changed (autodep), but don't re-run if the
# only thing that changed was the comments (cache.comments)
# - Don't clutter R output with messages or warnings (message, warning)
  # This _will_ leave error messages showing up in the knitted report

knitr::opts_chunk$set(echo = TRUE, 
                      cache = TRUE,
                      autodep = TRUE,
                      cache.comments = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      error = TRUE,
                      comment = NA)
```

Has RcppOctave been installed and loaded?
```{r}
library(RcppOctave)
.CallOctave("version")
```


```{r}
fX <- OctaveFunction("
function [X] = mvnrandom()
  pkg load statistics

  % First generate some 2-D multivariate normal
  % random variables, with mean MU and 
  % covariance SIGMA. This uses a Statistics
  % Toolbox function.

  n = 100;
  mu = [-2, 2];
  sigma = [1,.5;.5,1];
  X = mvnrnd(mu,sigma,n);
  % plot(X(:,1),X(:,2),'.')
end
")
```



```{r}
X <- fX()
dim(X)
```

```{r}
sphered <- OctaveFunction("function [Z] = sphered(X, n=100)
  % Now sphere the data.
  xbar = mean(X);

  % Get the eigenvectors and eigenvalues of the 
  % covariance matrix.
  [V,D] = eig(cov(X));

  % Center the data.
  Xc = X - ones(n,1)*xbar;

  % Sphere the data.
  Z = ((D)^(-1/2)*V'*Xc')';
  % plot(Z(:,1),Z(:,2),'.')
end                         
")
```

```{r}
Z <- sphered(X)
```

```{r}
plot(Z[,1], Z[,2])
```