---
title: "02-2 PCA Yeast - Octave"
output:
  html_document: default
  html_notebook: default
---

```{r setup, include=FALSE, error=TRUE, message=FALSE}
# Set knitr options for knitting code into the report:
# - Don't print out code (echo)
# - Save results so that code blocks aren't re-run unless code changes (cache),
# _or_ a relevant earlier code block changed (autodep), but don't re-run if the
# only thing that changed was the comments (cache.comments)
# - Don't clutter R output with messages or warnings (message, warning)
  # This _will_ leave error messages showing up in the knitted report

knitr::opts_chunk$set(echo = TRUE, 
                      cache = TRUE,
                      autodep = TRUE,
                      cache.comments = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      error = TRUE,
                      comment = NA)
```

```{r}
library(RcppOctave)
.CallOctave("version")
```

This loads the Matlab object `yeast`.
```{r}
f_pca_yeast <- OctaveFunction("
function [eigval, pervar, g, propvar, Xp] = scree()
  load yeast
  [n,p] = size(data);
  % Center the data.
  datac = data - repmat(sum(data)/n,n,1); 
  % Find the covariance matrix.
  covm = cov(datac);
  
  [eigvec,eigval] = eig(covm);
  eigval = diag(eigval); % Extract the diagonal elements
  % Order in descending order
  eigval = flipud(eigval);
  eigvec = eigvec(:,p:-1:1);
  
  % Now for the percentage of variance explained.
  pervar = 100*cumsum(eigval)/sum(eigval);
  
  % First get the expected sizes of the eigenvalues.
  g = zeros(1,p);
  for k = 1:p
     for i = k:p
        g(k) = g(k) + 1/i;
     end
  end
        g = g/p;
  
  propvar = eigval/sum(eigval);
  
  % Now for the size of the variance.
  avgeig = mean(eigval);
  % Find the length of ind:
  ind = find(eigval > avgeig);
  length(ind);
  
  % So, using 3, we will reduce the dimensionality.
  P = eigvec(:,1:3);
  Xp = datac*P;
  
  %% figure,plot3(Xp(:,1),Xp(:,2),Xp(:,3),'k*')
  %% xlabel('PC 1'),ylabel('PC 2'),zlabel('PC 3')
  %% grid on, axis tight
end  ")

```


```{r}
pca_yeast <- f_pca_yeast()
eigvale <- pca_yeast$eigval
Xp <- pca_yeast$Xp
```

```{r}
# Build scree plot
plot(1:length(eigvale), eigvale, 
     type = "l", 
     main = "Scree Plot",
     xlab = "Eigenvalue Index",
     ylab = "Eigenvalue")
points(1:length(eigvale), eigvale)
```

```{r fig.asp=1}
library("plot3D")

scatter3D(Xp[,1], Xp[,2], Xp[,3],
          col = "blue",
          pch = 19,
          cex = 0.5,
          bty = "b2",
          xlab = "PC1",
          ylab = "PC2",
          zlab = "PC3",
          theta = 30,       # 3D viewing direction: azimuth
          phi = 15,           # co-latitude
          ticktype = "detailed"
          )
```

